/*   Messages related to the CHESS library.
/*
msg err1
  lan english -def
    Missing token
    on line %p2i of file %p1s.
msg err2
  lan english -def
    Unrecognized token "%p3s" encountered
    on line %p2i of file %p1s.
msg err3
  lan english -def
    Too many tokens found on line %p2i of file %p1s.
msg err4
  lan english -def
    The private move evaluator failed to install an EVAL_MOVE routine on
    the call to CHESS_EVAL_OPEN.
